JDP221002-3
piotr-grosicki/project-jdp-2210-02 pull request #1
Opened 2022-09-29 18:55 UTC by kpodsiadlo7

Jeżeli tak to miało wyglądać to spoko. 
Wszystkie zapytania zwracają status 200.

2022-09-29 21:08 UTC, piotr-grosicki requested changes

2022-09-29 21:08 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/cart/CartController.java
> +    ResponseEntity<?> createEmptyCart(){
przydaloby sie jakies dto zeby zwrocic cos co ma sens :)

2022-09-30 20:28 UTC, kpodsiadlo7 commented on src/main/java/com/kodilla/ecommercee/cart/CartController.java
> +    ResponseEntity<?> createEmptyCart(){
Nie wiem czy teraz coś jeszcze muszę zrobić aby jakby wznowić zapytanie tego pull requesta, czy to już się zrobiło i tylko czekać na akceptację z Twojej strony, bądź kolejne uwagi

2022-10-01 16:50 UTC, piotr-grosicki requested changes

2022-10-01 16:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/cart/CartController.java
> +    ResponseEntity<Void> deleteProductFromCartById(@PathVariable Long id){
tutaj przydaly by sie dwa id, jeden dla produktu, drugi dla cart

2022-10-01 16:50 UTC, piotr-grosicki requested changes

2022-10-01 16:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/cart/CartController.java
> +    ResponseEntity<CartDto> addProductToCart(@PathVariable Long cartId){
tutaj przydaly by sie dwa id, jeden dla produktu, drugi dla cart

2022-10-02 20:31 UTC, piotr-grosicki approved these changes

2022-10-02 20:31 UTC, merged