JDP221002-14
piotr-grosicki/project-jdp-2210-02 pull request #10
Opened 2022-10-03 19:06 UTC by kpodsiadlo7

2022-10-05 20:30 UTC, Nessssscaf requested changes
dopisz adnotację @Column(name = "cart_id", unique = true) do Long id; żeby wymusić nazwę zgodnie ze schematem bazy danych

2022-10-05 21:28 UTC, lenczewskitom requested changes
Pole id powinno chyba jeszcze mieć adnotacja @NotNull + wydaje mi się, że wszystkie pola powinny mieć adnotacje @Column(name = )

2022-10-08 15:58 UTC, lenczewskitom approved these changes

2022-10-09 18:53 UTC, Nessssscaf approved these changes

2022-10-09 18:53 UTC, merged