JDP221002-17
piotr-grosicki/project-jdp-2210-02 pull request #15
Opened 2022-10-09 16:19 UTC by jacolec

Testy encji Product, drobne zmiany w samej encji.

2022-10-10 17:49 UTC, jacolec commented
Drobne poprawki w Product i ProductController

2022-10-10 18:10 UTC, kpodsiadlo7 reviewed
Zapomniałeś o @PathVariable Long productId w `@PutMapping(value = "{productId}")
    public ResponseEntity<ProductDto> updateProduct(@RequestBody ProductDto productDto)`

2022-10-10 18:33 UTC, jacolec commented
Już poprawione

2022-10-12 19:16 UTC, jacolec commented
Dodałem relację encji Product z encją Cart

2022-10-13 13:25 UTC, lenczewskitom requested changes
Coś jest nie tak, bo się nie buduje.
Na pewno trzeba zmienić konstruktor w encji Product - usunąć Id.
Wtedy zmienić tworzone obiekty Product w testach.

2022-10-14 16:30 UTC, closed without merging