JDP221002-18
piotr-grosicki/project-jdp-2210-02 pull request #18
Opened 2022-10-12 13:37 UTC by lenczewskitom

2022-10-13 13:47 UTC, kpodsiadlo7 requested changes
Przy @Entity nie powinno byc zadnego name

2022-10-13 18:54 UTC, Nessssscaf approved these changes

2022-10-15 20:37 UTC, jacolec approved these changes

2022-10-15 20:43 UTC, kpodsiadlo7 approved these changes

2022-10-15 20:44 UTC, merged