Task jdp221002 2
piotr-grosicki/project-jdp-2210-02 pull request #2
Opened 2022-09-30 10:03 UTC by lenczewskitom

2022-09-30 17:40 UTC, piotr-grosicki requested changes

2022-09-30 17:40 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/group/GroupController.java
> +    GroupDto updateGroup() {
brakuje parametru

2022-09-30 17:40 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/group/Group.java
> +public class Group {
encja nie powinna powstac w tym zadaniu

2022-10-03 08:10 UTC, lenczewskitom commented
Dodałem wymagane zmiany

2022-10-03 15:31 UTC, piotr-grosicki requested changes

2022-10-03 15:31 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/group/GroupController.java
> +    public void createGroup() {
wciaz

2022-10-03 16:13 UTC, lenczewskitom commented on src/main/java/com/kodilla/ecommercee/group/GroupController.java
> +    public void deleteGroup(Long groupId) {
Ok, już dodałem, nie wiem jak to przoczyłem...

2022-10-04 05:57 UTC, piotr-grosicki approved these changes

2022-10-04 05:57 UTC, merged