JDP221002-15
piotr-grosicki/project-jdp-2210-02 pull request #9
Opened 2022-10-03 19:01 UTC by kpodsiadlo7

2022-10-05 20:52 UTC, Nessssscaf requested changes
proponuję trzymać się adnotacji @Column

2022-10-05 21:26 UTC, lenczewskitom requested changes
Pole id powinno chyba jeszcze mieć adnotacja @NotNull + wydaje mi się, że wszystkie pola powinny mieć adnotacje @Column(name = )

2022-10-06 14:36 UTC, jacolec approved these changes

2022-10-08 15:58 UTC, lenczewskitom approved these changes

2022-10-09 18:53 UTC, Nessssscaf approved these changes

2022-10-09 18:53 UTC, merged